name: Deploy to FTP

on:
  push:
    branches:
      - main  # Passe den Branch an, den du überwachen möchtest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Codes
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Passe die Node.js-Version an

      # Build ausführen
      - name: Build project
        run: |
          cd frontend
          npm install
          npm run build

      # Dateien auf den FTP-Server hochladen
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Korrekte Version angeben
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist  # Passe dies an deinen Build-Ordner an
          server-dir: ${{ secrets.FTP_PATH }}  # Optional: Zielpfad auf dem FTP-Server
